name: CURL CLI ACTION
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: --request POST --url https://backboard.railway.app/graphql/v2 --header 'Authorization: Bearer ${{RAILWAY_API_TOKEN}}' --header 'Content-Type: application/json' --data mutation deploymentRemove {deploymentRemove(id: "fdd751d7-8af2-4971-aaea-be6f62ba5be4")}
